name: Update Documentation

on:
  push:
    paths:
      - '**/airflow_dags/**'

jobs:
  update_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Update Documentation
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

        for p in $CHANGED_FILES; do
          if [[ "$p" == *"airflow_dags"* ]]; then
            COMMIT_ID=$(git rev-parse HEAD)
            COMMIT_DATE=$(git show --no-patch --format=%ci $COMMIT_ID)
            COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')

            file_path="$p"

            sed -i "s/Last Git commit:.*/Last Git commit: ${COMMIT_ID}/" "$file_path"
            sed -i "s/Date of last commit:.*/Date of last commit: ${COMMIT_DATE}/" "$file_path"
            sed -i "s/Author of last commit:.*/Author of last commit: ${COMMIT_AUTHOR}/" "$file_path"

            git add "$file_path"
            git commit -m "Update documentation of ${p} with latest commit"
          fi
        done

    - name: Push Changes
      if: success()
      run: git push origin HEAD:main
