name: Post-Merge Script

on:
  push:
     branches:
      - main

jobs:
  post_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Debugging
      run: |
        ls -al
        git log --oneline -n 2

    - name: Run Post-Merge Script
      run: |
            sed "5s/.*/Last Git commit: BBBBB/" "src/python/airflow_dags/tuto.py" > temp && mv temp "src/python/airflow_dags/tuto.py"
            
            git config --global user.email "dprykh@softserveinc.com"
            git config --global user.name "Denys Prykhodko"

            git pull
            git status
            git add .
            git commit -m "message1"
            git push origin main
    - name: Status check
      run: |
        git status
        git log --oneline -n 3
